### ISSUE TITLE
bug: lookup 0.0.0: no such host

### ISSUE THREAD

**Issue by flohoss** [logto-io/go#107]
### Describe the bug
`[GIN-debug] [ERROR] listen tcp: lookup 0.0.0: no such host`

### Expected behavior
Gin to start on 0.0.0.0 with port 8080

### How to reproduce?
Run code in docker

```yaml
services:
  go:
    build:
      context: .
      dockerfile_inline: |
        FROM golang:1.22-alpine
        RUN apk add git
        WORKDIR /app
        RUN git clone https://github.com/logto-io/go.git
        WORKDIR /app/go/gin-sample
        RUN go mod download
        CMD go run .
    ports:
      - 8080:8080
```
